# Generated by Django 4.2.27 on 2026-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysUser",
            fields=[
                (
                    "user_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="用户ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="密码哈希（SM3）"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        default=1, verbose_name="状态（0-禁用，1-启用）"
                    ),
                ),
                (
                    "login_fail_count",
                    models.IntegerField(default=0, verbose_name="登录失败次数"),
                ),
                (
                    "lock_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="锁定截止时间"
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="消息数量"),
                ),
                (
                    "total_tokens",
                    models.BigIntegerField(default=0, verbose_name="总Token数"),
                ),
                (
                    "last_active_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后活跃时间"
                    ),
                ),
                (
                    "last_login_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="最后登录IP"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统用户",
                "verbose_name_plural": "系统用户",
                "db_table": "sys_user",
                "indexes": [models.Index(fields=["username"], name="uk_username")],
            },
        ),
    ]
