# Generated by Django 4.2.27 on 2026-01-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sysuser",
            name="uk_username",
        ),
    ]
