# Generated by Django 4.2.27 on 2026-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_sysuser_uk_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="type",
            field=models.CharField(
                choices=[("admin", "管理员"), ("user", "普通用户")],
                default="user",
                max_length=20,
                verbose_name="用户类型",
            ),
        ),
    ]
