# Generated by Django 4.2.27 on 2026-01-29 09:52

from django.db import migrations


def set_admin_type(apps, schema_editor):
    """将 username='admin' 的用户设为管理员类型"""
    SysUser = apps.get_model("users", "SysUser")
    SysUser.objects.filter(username="admin").update(type="admin")


def reverse_admin_type(apps, schema_editor):
    """回滚：将管理员重置为普通用户"""
    SysUser = apps.get_model("users", "SysUser")
    SysUser.objects.filter(username="admin").update(type="user")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_type_field"),
    ]

    operations = [
        migrations.RunPython(set_admin_type, reverse_admin_type),
    ]
