# Generated by Django 4.2.27 on 2026-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_set_admin_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="guest_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="访客有效期截止时间"
            ),
        ),
        migrations.AddField(
            model_name="sysuser",
            name="member_type",
            field=models.CharField(
                choices=[("member", "成员"), ("guest", "访客")],
                default="member",
                max_length=20,
                verbose_name="业务类型（member/guest）",
            ),
        ),
    ]
