# Generated by Django 4.2.27 on 2026-01-29 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("language", "语言模型"), ("embedding", "向量模型")],
                        max_length=20,
                        verbose_name="模型类型",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("url", models.CharField(max_length=500, verbose_name="API 基础地址")),
                (
                    "api_key",
                    models.CharField(
                        max_length=500, verbose_name="API Key（SM4 加密存储）"
                    ),
                ),
                (
                    "max_context_window",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最大上下文窗口（token 数）",
                    ),
                ),
                (
                    "max_input_tokens",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最大输入 token 数",
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最大输出 token 数",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="温度参数",
                    ),
                ),
                (
                    "top_p",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Top-P 采样",
                    ),
                ),
                (
                    "frequency_penalty",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="频率惩罚",
                    ),
                ),
                (
                    "presence_penalty",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="存在惩罚",
                    ),
                ),
                (
                    "embedding_dimensions",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="向量维度（仅 embedding 类型有效）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="是否激活（系统管理，不可编辑）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "模型配置",
                "verbose_name_plural": "模型配置",
                "db_table": "model",
            },
        ),
    ]
