# Generated by Django 4.2.27 on 2026-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_add_multimodal_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("tool", "工具模型"),
                    ("multimodal", "多模态模型"),
                    ("embedding", "向量模型"),
                ],
                max_length=20,
                verbose_name="模型类型",
            ),
        ),
    ]
