# Generated by Django 4.2.27 on 2026-02-24 03:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_set_admin_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wake_words",
                    models.JSONField(default=list, verbose_name="唤醒词列表"),
                ),
                (
                    "recording_mode",
                    models.CharField(
                        choices=[("hold", "按住说话"), ("toggle", "点击切换")],
                        default="toggle",
                        max_length=10,
                        verbose_name="录音模式",
                    ),
                ),
                (
                    "vad_sensitivity",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="VAD灵敏度（0.0-1.0）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_settings",
                        to="users.sysuser",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "语音设置",
                "verbose_name_plural": "语音设置",
                "db_table": "voice_settings",
            },
        ),
        migrations.CreateModel(
            name="SpeakerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway_speaker_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="llmgateway 声纹用户ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="显示名称")),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="声纹质量评分（0.0-1.0）"
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="声纹注册时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_profile",
                        to="users.sysuser",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "声纹档案",
                "verbose_name_plural": "声纹档案",
                "db_table": "voice_speaker_profile",
            },
        ),
        migrations.CreateModel(
            name="RegisteredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_uuid",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="设备公开标识"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                (
                    "api_token_encrypted",
                    models.CharField(max_length=512, verbose_name="SM4加密的API Token"),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        db_index=True,
                        max_length=8,
                        verbose_name="Token前8位（快速查找）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后活跃时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_devices",
                        to="users.sysuser",
                        verbose_name="设备注册者",
                    ),
                ),
            ],
            options={
                "verbose_name": "注册设备",
                "verbose_name_plural": "注册设备",
                "db_table": "voice_registered_device",
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_active"], name="idx_device_user_active"
                    )
                ],
            },
        ),
    ]
