# Generated by Django 4.2.27 on 2026-02-28 03:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_set_admin_type"),
        ("voice", "0002_create_unknown_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registereddevice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="speakerprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="voicesettings",
            options={},
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="api_token_encrypted",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="device_uuid",
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="last_active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="token_prefix",
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_devices",
                to="users.sysuser",
            ),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="enrolled_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="gateway_speaker_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_profile",
                to="users.sysuser",
            ),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="recording_mode",
            field=models.CharField(
                choices=[("hold", "按住说话"), ("toggle", "点击切换")],
                default="toggle",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_settings",
                to="users.sysuser",
            ),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="vad_sensitivity",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="wake_words",
            field=models.JSONField(default=list),
        ),
    ]
