# Generated by Django 4.2.27 on 2026-04-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0003_alter_registereddevice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicesettings",
            name="ha_speaker_entity_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="voicesettings",
            name="tts_output_device",
            field=models.CharField(
                choices=[("browser", "浏览器"), ("ha_speaker", "HA 音箱")],
                default="browser",
                max_length=20,
            ),
        ),
    ]
