# Generated by Django 4.2.27 on 2026-03-05 02:23

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        # pgvector 扩展（幂等）
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="",  # 不删除扩展
        ),
        migrations.AddField(
            model_name="mediaattachment",
            name="embedding_status",
            field=models.CharField(
                choices=[
                    ("none", "未生成"),
                    ("pending", "待生成"),
                    ("processing", "生成中"),
                    ("done", "已完成"),
                    ("failed", "失败"),
                ],
                default="none",
                max_length=20,
                verbose_name="分块Embedding状态",
            ),
        ),
        migrations.AddField(
            model_name="mediaattachment",
            name="parsed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="解析完成时间"
            ),
        ),
        migrations.AddField(
            model_name="mediaattachment",
            name="parsed_content",
            field=models.TextField(blank=True, null=True, verbose_name="解析结果全文"),
        ),
        migrations.AddField(
            model_name="mediaattachment",
            name="parsed_content_path",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="MinIO解析结果备份路径",
            ),
        ),
        migrations.AddField(
            model_name="mediaattachment",
            name="parsed_content_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="解析结果字节数"
            ),
        ),
        migrations.CreateModel(
            name="DocumentChunkEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="用户ID（冗余，加速查询）"
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(default=0, verbose_name="分块序号"),
                ),
                ("chunk_text", models.TextField(verbose_name="分块文本")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1024, null=True, verbose_name="1024维语义向量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_embeddings",
                        to="media.mediaattachment",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档分块向量",
                "verbose_name_plural": "文档分块向量",
                "db_table": "document_chunk_embedding",
                "indexes": [
                    models.Index(fields=["attachment_id"], name="idx_dce_attachment"),
                    models.Index(fields=["user_id"], name="idx_dce_user"),
                ],
            },
        ),
        # GIN 全文索引: parsed_content jiebacfg 分词
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_attachment_parsed_content_gin
                ON media_attachment
                USING gin(to_tsvector('jiebacfg', COALESCE(parsed_content, '')))
                WHERE parsed_content IS NOT NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_attachment_parsed_content_gin;",
        ),
    ]
