# Generated by Django 4.2.27 on 2026-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="消息ID"
                    ),
                ),
                (
                    "message_uuid",
                    models.CharField(
                        db_index=True,
                        max_length=36,
                        unique=True,
                        verbose_name="消息UUID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="用户ID（数据隔离）"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "助手"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="请求ID（链路追踪）",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应耗时（毫秒）"
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="提示Token数"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="完成Token数"),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="模型名称"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, null=True, verbose_name="扩展数据"),
                ),
                (
                    "sequence",
                    models.IntegerField(db_index=True, verbose_name="用户内递增序号"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "失败"), (1, "正常"), (2, "生成中"), (3, "中断")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "db_table": "message",
                "ordering": ["created_time"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "sequence"], name="idx_user_sequence"
                    ),
                    models.Index(
                        fields=["user_id", "created_time"], name="idx_user_created"
                    ),
                    models.Index(fields=["request_id"], name="idx_request_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LangGraphExecution",
            fields=[
                (
                    "execution_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="执行ID"
                    ),
                ),
                (
                    "execution_uuid",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="执行UUID"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="请求ID（关联message）",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(db_index=True, verbose_name="用户ID"),
                ),
                (
                    "thread_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="线程ID（user_{user_id}）",
                    ),
                ),
                ("graph_name", models.CharField(max_length=100, verbose_name="图名称")),
                (
                    "run_id",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="运行ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="执行耗时（毫秒）"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(blank=True, null=True, verbose_name="输入数据"),
                ),
                (
                    "output_data",
                    models.JSONField(blank=True, null=True, verbose_name="输出数据"),
                ),
                (
                    "node_executions",
                    models.JSONField(
                        blank=True, null=True, verbose_name="节点执行详情"
                    ),
                ),
                (
                    "total_prompt_tokens",
                    models.IntegerField(default=0, verbose_name="总提示Token数"),
                ),
                (
                    "total_completion_tokens",
                    models.IntegerField(default=0, verbose_name="总完成Token数"),
                ),
                (
                    "llm_call_count",
                    models.IntegerField(default=0, verbose_name="LLM调用次数"),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="错误类型"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "langfuse_trace_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Langfuse追踪ID",
                    ),
                ),
                (
                    "langfuse_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Langfuse链接",
                    ),
                ),
            ],
            options={
                "verbose_name": "LangGraph执行记录",
                "verbose_name_plural": "LangGraph执行记录",
                "db_table": "langgraph_execution",
                "indexes": [
                    models.Index(fields=["request_id"], name="idx_exec_request_id"),
                    models.Index(fields=["user_id"], name="idx_exec_user_id"),
                    models.Index(fields=["thread_id"], name="idx_exec_thread_id"),
                ],
            },
        ),
    ]
