# Generated by Django 4.2.27 on 2026-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_time",
            field=models.DateTimeField(db_index=True, verbose_name="创建时间"),
        ),
    ]
