# Generated by Django 4.2.27 on 2026-02-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_add_media_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaattachment",
            name="thumbnail_path",
        ),
        migrations.AlterField(
            model_name="mediaattachment",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "图片"),
                    ("video", "视频"),
                    ("audio", "音频"),
                    ("document", "文档"),
                ],
                max_length=20,
                verbose_name="媒体类型",
            ),
        ),
    ]
