# Generated by Django 4.2.27 on 2026-02-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_thumbnail_add_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_voice",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="语音消息标记"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="speaker_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="说话人ID（llmgateway声纹识别）",
            ),
        ),
    ]
