# Generated by Django 4.2.27 on 2026-02-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_mediaattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="langgraphexecution",
            name="duration_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="error_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="execution_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="execution_uuid",
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="graph_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="input_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="langfuse_trace_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="langfuse_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="llm_call_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="node_executions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="output_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="request_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="run_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "运行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="thread_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="total_completion_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="total_prompt_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="langgraphexecution",
            name="user_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="completion_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_voice",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_uuid",
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="model_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="prompt_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="response_time_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sequence",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="speaker_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "失败"), (1, "正常"), (2, "生成中"), (3, "中断")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
