# Generated by Django 4.2.27 on 2026-01-31 18:52

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # T008: 启用 pgvector 扩展
        VectorExtension(),
        # T008: 创建 pg_jieba 全文搜索配置（退化方案：simple 配置）
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- 尝试创建 pg_jieba 扩展
                BEGIN
                    CREATE EXTENSION IF NOT EXISTS pg_jieba;
                EXCEPTION WHEN OTHERS THEN
                    RAISE WARNING 'pg_jieba 不可用，将退化为 simple 分词配置: %', SQLERRM;
                END;
                -- 创建 jiebacfg 搜索配置
                IF NOT EXISTS (
                    SELECT 1 FROM pg_ts_config WHERE cfgname = 'jiebacfg'
                ) THEN
                    BEGIN
                        CREATE TEXT SEARCH CONFIGURATION jiebacfg (PARSER = jieba);
                        ALTER TEXT SEARCH CONFIGURATION jiebacfg
                            ADD MAPPING FOR n,v,a,i,e,l,j WITH simple;
                    EXCEPTION WHEN OTHERS THEN
                        RAISE WARNING 'jiebacfg 创建失败，退化为 simple: %', SQLERRM;
                        -- 退化方案：使用 simple 配置
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_ts_config WHERE cfgname = 'jiebacfg'
                        ) THEN
                            CREATE TEXT SEARCH CONFIGURATION jiebacfg (COPY = simple);
                        END IF;
                    END;
                END IF;
            END
            $$;
            """,
            reverse_sql="DROP TEXT SEARCH CONFIGURATION IF EXISTS jiebacfg;",
        ),
        migrations.CreateModel(
            name="UserMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="记忆ID"
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="用户ID（数据隔离）"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("memory", "用户记忆"),
                            ("compaction", "上下文压缩"),
                            ("daily-summary", "每日总结"),
                            ("monthly-summary", "每月总结"),
                        ],
                        default="memory",
                        max_length=20,
                        verbose_name="记忆类型",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="名称"
                    ),
                ),
                ("content", models.TextField(verbose_name="记忆文本")),
                (
                    "embedding_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("done", "完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Embedding状态",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试计数"),
                ),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="标签")),
                (
                    "importance_score",
                    models.FloatField(blank=True, null=True, verbose_name="重要性评分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户记忆",
                "verbose_name_plural": "用户记忆",
                "db_table": "user_memory",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMemoryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="向量记录ID"
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="用户ID（冗余，加速查询）"
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="类型（冗余）")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="名称（冗余）",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(default=0, verbose_name="分块序号"),
                ),
                (
                    "chunk_text",
                    models.TextField(blank=True, null=True, verbose_name="分块文本"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True, verbose_name="向量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="memory.usermemory",
                        verbose_name="关联记忆",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户记忆向量",
                "verbose_name_plural": "用户记忆向量",
                "db_table": "user_memory_embedding",
            },
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(
                fields=["embedding_status"], name="idx_um_embedding_status"
            ),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(fields=["user_id", "type"], name="idx_um_user_type"),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(
                fields=["embedding_status", "retry_count"], name="idx_um_status_retry"
            ),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(
                fields=["user_id", "created_at"], name="idx_um_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="usermemoryembedding",
            index=models.Index(fields=["memory_id"], name="idx_ume_memory"),
        ),
        # T009: GIN 索引 — pg_jieba 中文全文检索（content tsvector）
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_um_content_tsv
            ON user_memory
            USING GIN (to_tsvector('jiebacfg', content));
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_um_content_tsv;",
        ),
    ]
