# Generated by Django 4.2.27 on 2026-02-03 02:40

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermemory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="embedding_status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("done", "完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="importance_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="type",
            field=models.CharField(
                choices=[
                    ("memory", "用户记忆"),
                    ("compaction", "上下文压缩"),
                    ("daily-summary", "每日总结"),
                    ("monthly-summary", "每月总结"),
                ],
                default="memory",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="user_id",
            field=models.BigIntegerField(db_index=True, verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="chunk_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="chunk_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="memory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="memory.usermemory",
            ),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="usermemoryembedding",
            name="user_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
